### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Matto244** [Stochalt/Wemod-Premium-Unlocker#2]
Launching WeMod Pro Unlocker...
C:\Users\Matteo\Wemod-Premium-Unlocker\Wemod-Premium-Unlocker\Wemod_ProUnlocker.py:45: SyntaxWarning: invalid escape sequence '\ '
  WEMOD_ASCII = """
Integrity check failed! The script has been modified. SKID.
[ERROR] Failed to launch WeMod Pro Unlocker.
==========================================================

**Comment by Stochalt** [comment]
Reinstall it and don't touch anything, just follow the instructions.
