### ISSUE TITLE
wemod updating 

### ISSUE THREAD

**Issue by SoaringEagle49** [Stochalt/Wemod-Premium-Unlocker#3]
the first time i ran this it worked correctly but mods would not install but every time since wemod updates from 8,20 no matter what i try

**Comment by Friendlyx3** [comment]
1)Install it and prevent it from updating by immediately closing it when it tries to update.
Alternatively, open the installer with your internet disabled or ethernet/wifi disconnected. It will say you aren't connected to the internet but will install anyway. Close the window.

2)Go to <user>/AppData/Local/WeMod and rename Update.exe to Update1.exe or delete it entirely.
3)Extract the unlocker python files into that same folder and run start.bat
